/**
 * Created by renminghe on 2017/3/8.
 */
module.exports = {
  val : ["UHostId",
    "Zone",
    "OsName",
    "ImageId",
    "BasicImageId",
    "BasicImageName",
    "Tag",
    "Name",
    "Remark",
    "State",
    "NetworkState",
    "StorageType",
    "TotalDiskSpace",
    "DiskSet",
    "NetCapability",
    "IPSet",
    "SubnetType",
    "ChargeType",
    "ExpireTime",
    "AutoRenew",
    "IsExpire",
    "UHostType",
    "OsType",
    "CreateTime",
    "CPU",
    "GPU",
    "Memory",
    "TimemachineFeature",
    "HotplugFeature",
    "NetCapFeature",
    "BootDiskState"],
};